---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: visit-service
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: visit-service@sha256:d1aebbb888f504f911f38a11c2d88d6d38cbcaa429a2bf8409166efc631e2509
        namespace: petclinic-s2i
      name: 1.5.9
